channels:
  - conda-forge

dependencies:
  # Items required for basic level functionality
  - gh-scoped-creds==4.1
  # DH-418, bunch of stuff fails to install if git is set higher to this e.g. git==2.47.1
  - git
  - jupyter-archive==3.4.0
  - jupyter-resource-usage==1.2.0
  - jupyter-server-proxy==4.4.0
  - jupyter_server==2.17.0
  - jupyterhub==5.4.2
  - jupyterlab==4.5.3
  - jupyterlab-git==0.51.3
  - jupyter-offlinenotebook==0.3.2
  - jupyterlab_rise==0.43.1
  - jupytext==1.18.1
  - nbgitpuller==1.2.2
  - notebook==7.5.3
  - pip==26.0.1
  - otter-grader==6.1.6
  - wrapt==1.17.3
  # Using python 3.11 for maximum compatibility with conda packages.
  - python==3.11
  # datascience packages
  - datascience==0.18.1
  - numpy==2.4.2
  - pandas==3.0.0
  - plotly==6.5.0
  - scikit-learn==1.8.0
  - scipy==1.17.0
  - seaborn==0.13.2
  - statsmodels==0.14.6
  - matplotlib==3.10.3
  # DH-654 conflicts with git-crendential-helpers
  - pyjwt==2.10.1

  # For https://github.com/berkeley-dsep-infra/datahub/issues/1846
  # Conda does not have these
  - pip:
      - git-credential-helpers==0.2
      - nbconvert[webpdf]==7.17.0
